package io.natskt.api

import io.natskt.internal.ServerOperation

public data class ServerInfo(
	val serverId: String,
	val serverName: String,
	val version: String,
	val go: String,
	val host: String,
	val port: Int,
	val headers: Boolean,
	val maxPayload: Int,
	val proto: Int,
	val clientId: Long?,
	val authRequired: Boolean?,
	val tlsRequired: Boolean?,
	val tlsVerify: Boolean?,
	val tlsAvailable: Boolean?,
	val connectUrls: List<String>?,
	val wsConnectUrls: List<String>?,
	val ldm: Boolean?,
	val gitCommit: String?,
	val jetstream: Boolean?,
	val ip: String?,
	val clientIp: String?,
	val nonce: String?,
	val cluster: String?,
	val domain: String?,
	val xkey: String?,
)

internal fun ServerOperation.InfoOp.toPublicApi(): ServerInfo =
	ServerInfo(
		serverId = this.serverId,
		serverName = this.serverName,
		version = this.version,
		go = this.go,
		host = this.host,
		port = this.port,
		headers = this.headers,
		maxPayload = this.maxPayload,
		proto = this.proto,
		clientId = this.clientId,
		authRequired = this.authRequired,
		tlsRequired = this.tlsRequired,
		tlsVerify = this.tlsVerify,
		tlsAvailable = this.tlsAvailable,
		connectUrls = this.connectUrls,
		wsConnectUrls = this.wsConnectUrls,
		ldm = this.ldm,
		gitCommit = this.gitCommit,
		jetstream = this.jetstream,
		ip = this.ip,
		clientIp = this.clientIp,
		nonce = this.nonce,
		cluster = this.cluster,
		domain = this.domain,
		xkey = this.xkey,
	)
